/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// RoleApplyConfiguration represents a declarative configuration of the Role type for use
// with apply.
type RoleApplyConfiguration struct {
	Name           *string                            `json:"name,omitempty"`
	Replicas       *int32                             `json:"replicas,omitempty"`
	EntryTemplate  *PodTemplateSpecApplyConfiguration `json:"entryTemplate,omitempty"`
	WorkerReplicas *int32                             `json:"workerReplicas,omitempty"`
	WorkerTemplate *PodTemplateSpecApplyConfiguration `json:"workerTemplate,omitempty"`
	MaxUnavailable *intstr.IntOrString                `json:"maxUnavailable,omitempty"`
}

// RoleApplyConfiguration constructs a declarative configuration of the Role type for use with
// apply.
func Role() *RoleApplyConfiguration {
	return &RoleApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RoleApplyConfiguration) WithName(value string) *RoleApplyConfiguration {
	b.Name = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *RoleApplyConfiguration) WithReplicas(value int32) *RoleApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithEntryTemplate sets the EntryTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EntryTemplate field is set to the value of the last call.
func (b *RoleApplyConfiguration) WithEntryTemplate(value *PodTemplateSpecApplyConfiguration) *RoleApplyConfiguration {
	b.EntryTemplate = value
	return b
}

// WithWorkerReplicas sets the WorkerReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkerReplicas field is set to the value of the last call.
func (b *RoleApplyConfiguration) WithWorkerReplicas(value int32) *RoleApplyConfiguration {
	b.WorkerReplicas = &value
	return b
}

// WithWorkerTemplate sets the WorkerTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkerTemplate field is set to the value of the last call.
func (b *RoleApplyConfiguration) WithWorkerTemplate(value *PodTemplateSpecApplyConfiguration) *RoleApplyConfiguration {
	b.WorkerTemplate = value
	return b
}

// WithMaxUnavailable sets the MaxUnavailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxUnavailable field is set to the value of the last call.
func (b *RoleApplyConfiguration) WithMaxUnavailable(value intstr.IntOrString) *RoleApplyConfiguration {
	b.MaxUnavailable = &value
	return b
}
